#Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

max_fib = 4_000_000
current_fib = 0
n1, n2 = 0, 1
dividend = 2
even_sum = 0


while current_fib < max_fib:
    
    current_fib = n1 + n2
    n1 = n2
    n2 = current_fib
    if current_fib % dividend == 0:
        even_sum += current_fib
        print(f'{current_fib} HIT')
    else:
        print(current_fib)
print(even_sum)