package main

import "fmt"

// https://leetcode.com/problems/find-the-difference
// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
// Example 1:
//   Input: s = "abcd", t = "abcde"
//   Output: "e"
//   Explanation: 'e' is the letter that was added.
// Example 2:
//   Input: s = "", t = "y"
//   Output: "y"

func findTheDifference(source string, target string) byte {
	charFrequency := make(map[byte]int)

	for i := 0; i < len(source); i++ {
		currentChar := source[i]
		charFrequency[currentChar]++
	}

	for i := 0; i < len(target); i++ {
		currentChar := target[i]
		charFrequency[currentChar]--
		if charFrequency[currentChar] < 0 {
			return currentChar
		}
	}
	return 0
}

func main() {
	s := "abcd"
	t := "abcdradf"
	x := findTheDifference(s, t)

	fmt.Printf("Missing letter %v\n", string(x))

}
